# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: rappdw/docker-java-python
      
    working_directory: ~/custom-example-python-circle

    steps:
      - checkout
   #   - run: 
     #     name: install dependencies
      #   command: | 
       #     pip install --upgrade pip
        #    python -m venv venv
         #   . venv/bin/activate
          #  pip install -r requirements.txt
      - run: 
            name: install dependencies
            command: | 
              sudo pip install pipenv
              pipenv install
      - run: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle/scripts/upload)
   #   - run: bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)

